apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: beta.kubernetes.io/os
            operator: In
            values:
            - "linux"
  containers:
  - image: nginx
    name: nginx
